server:
  port: 8081


aliyun:
  oss:
    endpoint: http://oss-cn-hangzhou.aliyuncs.com
    accessKeyId: yourAccessKeyId
    accessKeySecret: 123456
    bucketName: feihong

logging:
  level:
    edu.scau.mis_pos.mapper: TRACE
    root: INFO
  file:
    name: isdp.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

spring:
  devtools:
    restart:
      enabled: true
  # 数据源
  datasource:
    # 连接池hikari
    type: com.zaxxer.hikari.HikariDataSource
    # 驱动程序
    driverClassName: com.mysql.cj.jdbc.Driver
    # 连接参数
    url: jdbc:mysql://localhost:3306/isdp?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 2018020008

